# lint this file using
# https://gitlab.com/ci/lint
image: cypress/base
cypress-e2e:
  stage: test
  script:
    - npm install
    - $(npm bin)/cypress run
  cache:
    untracked: true
    paths:
    - node_modules/
  artifacts:
    expire_in: 1 week
    paths:
    - cypress/screenshots
    - cypress/videos
